id: d426af6f41504b28909937cbd7778a67
title: Toh_54-The_Exposition_on_the_Universal_Gateway-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-040-005
  eft-text-version: 1.0.7 2021
